language: node_js
node_js: node
before_install:
  - cd backend && npm install
  - cd ../frontend && npm install
  - cd ..
env:
  - CXX=g++-7
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-7
      - libc6-dev
