language: node_js
node_js: node
before_install:
  - cd backend && npm install
  - cd ../frontend && npm install
  - cd ..
env:
  - CXX=clang
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - clang
      - libc6
