version: "3.8"

services:
  talentbook-frontend:
    image: talentbook-frontend:latest
    container_name: talentbook_frontend
    restart: always
    environment:
      - API_URL=http://talentbook_backend:8001
    depends_on:
      - talentbook-backend
    ports:
      - ${FRONTEND_PORT}:8000
  talentbook-backend:
    image: talentbook-backend:latest
    container_name: talentbook_backend
    environment:
      - SMTP_HOST
      - SMTP_PORT
      - SMTP_USER
      - SMTP_PASSWORD
      - SMTP_SECURE
      - DB_TYPE=postgres
      - DB_HOST=db
      - DB_NAME=talentbook
      - DB_USER=talentbook
      - DB_PASSWORD=talentbook
      - FRONTEND_URL
      - EMAIL_FROM
    command: npm start
    restart: always
    depends_on:
      - db
  db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_DB=talentbook
      - POSTGRES_USER=talentbook
      - POSTGRES_PASSWORD=talentbook
    volumes:
      - pgdata:/var/lib/postgresql/data
  adminer:
    image: adminer
    restart: always
    profiles:
      - dev
    ports:
      - ${ADMINER_PORT}:8080
  smtp4dev:
    image: rnwood/smtp4dev:v3
    restart: always
    profiles:
      - dev
    ports:
      - ${SMTP4DEV_PORT}:80
      - 25:25
      - 143:143
    volumes:
      - smtp4dev-data:/smtp4dev
    environment:
      # More options see https://github.com/rnwood/smtp4dev/blob/master/docker-compose.yml
      - ServerOptions__HostName=smtp4dev
volumes:
  pgdata:
  smtp4dev-data:
