openapi: "3.0.2"
info:
  version: 1.0.0
  title: TalentBook API
  license:
    name: MIT
servers:
  - url: http://localhost:1337/api
components:
  securitySchemes:
    cookieAuth:
      name: talentbook_authtoken
      type: apiKey
      in: cookie    
  schemas:
    VersionInfo:
      $ref: 'schemas/version-info.yaml'
    Credentials:
      $ref: 'schemas/credentials.yaml'
    Identity:
      $ref: 'schemas/identity.yaml'
    User:
      $ref: 'schemas/user.yaml'
    Skill:
      $ref: 'schemas/skill.yaml'
    Users:
      $ref: 'schemas/users.yaml'
    Error:
      $ref: 'schemas/error.yaml'
    Success:
      $ref: 'schemas/success.yaml'
    Query:
      $ref: 'schemas/query.yaml'
    ResultList:
      $ref: 'schemas/result-list.yaml'
paths:
  /version:
    $ref: 'paths/version.yaml'
  /signup:
    $ref: 'paths/sign-up.yaml'
  /login:
    $ref: 'paths/login.yaml'
  /logout:
    $ref: 'paths/logout.yaml'
  /user:
    $ref: 'paths/user.yaml'
  /query:
    $ref: 'paths/query.yaml'
  
