openapi: '3.0.2'
info:
  version: 1.0.0
  title: TalentBook API
  license:
    name: MIT
servers:
  - url: http://localhost:1337/api
components:
  securitySchemes:
    cookieAuth:
      name: talentbook_authtoken
      type: apiKey
      in: cookie
  schemas:
    VersionInfo:
      $ref: 'schemas/version-info.yaml'
    Credentials:
      $ref: 'schemas/credentials.yaml'
    Identity:
      $ref: 'schemas/identity.yaml'
    User:
      $ref: 'schemas/user.yaml'
    Users:
      $ref: 'schemas/users.yaml'
    UserSkill:
      $ref: 'schemas/user-skill.yaml'
    Skill:
      $ref: 'schemas/skill.yaml'
    Skills:
      $ref: 'schemas/skills.yaml'
    Error:
      $ref: 'schemas/error.yaml'
    Success:
      $ref: 'schemas/success.yaml'
    Query:
      $ref: 'schemas/query.yaml'
    ResultItem:
      $ref: 'schemas/result-item.yaml'
    ResultList:
      $ref: 'schemas/result-list.yaml'
    Team:
      $ref: 'schemas/team.yaml'
    Teams:
      $ref: 'schemas/teams.yaml'
    TeamDetails:
      $ref: 'schemas/team-details.yaml'
paths:
  /version:
    $ref: 'paths/version.yaml'
  /signup:
    $ref: 'paths/sign-up.yaml'
  /login:
    $ref: 'paths/login.yaml'
  /logout:
    $ref: 'paths/logout.yaml'
  /user/{name}:
    $ref: 'paths/user_name.yaml'
  /user/{name}/skills:
    $ref: 'paths/user_name_skills.yaml'
  /user/{name}/skill:
    $ref: 'paths/user_name_skill.yaml'
  /user/{name}/skill/{skillName}:
    $ref: 'paths/user_name_skill_skillname.yaml'
  /query:
    $ref: 'paths/query.yaml'
  /skills:
    $ref: 'paths/skills.yaml'
  /skill:
    $ref: 'paths/skill.yaml'
  /skill/{name}:
    $ref: 'paths/skill_name.yaml'
  /team:
    $ref: 'paths/team.yaml'
  /teams:
    $ref: 'paths/teams.yaml'
  /team/{name}:
    $ref: 'paths/team_name.yaml'
